name: Rename the project from template

on: [push]

permissions: write-all

jobs:
  rename-project:
    if: ${{ !contains (github.repository, '/RWModTemplate') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}' | tr '-' ' ')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_URLNAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - run: echo "REPOSITORY_OWNER=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash

      - name: Get repository description
        uses: actions/github-script@v6
        id: get_description
        with:
          script: |
            const response = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return response.data.description;
          result-encoding: string

      - run: echo "REPOSITORY_DESCRIPTION=$(echo '${{ steps.get_description.outputs.result }}')" >> $GITHUB_ENV
        shell: bash
        
      - name: Is this still a template
        id: is_template
        run: echo "::set-output name=is_template::$(ls .github/template.yml &> /dev/null && echo true || echo false)"

      - name: Rename the project
        if: steps.is_template.outputs.is_template == 'true'
        run: |
          echo "Renaming the project with -a(author) ${{ env.REPOSITORY_OWNER }} -n(name) ${{ env.REPOSITORY_NAME }} -u(urlname) ${{ env.REPOSITORY_URLNAME }}"
          .github/rename_project.sh -a ${{ env.REPOSITORY_OWNER }} -n "${{ env.REPOSITORY_NAME }}" -u ${{ env.REPOSITORY_URLNAME }} -d "${{ env.REPOSITORY_DESCRIPTION }}"
              
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Applied template changes."
          # commit_options: '--amend --no-edit'
          push_options: --force
